services:
  crawler:
    build:
      context: ../crawler
      dockerfile: Dockerfile
    hostname: crawler
    container_name: pc-crawler
    expose:
      - 8080
    tty: true
    volumes:
      - ../crawler:/workspace
      - paper-crawler-volume:/workspace/volume

volumes:
  paper-crawler-volume:
    driver: local