services:
  paper-crawler-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: paper-crawler-dev
    container_name: paper-crawler-dev
    expose:
      - 8080
    tty: true
    volumes:
      - ..:/workspace
      - paper-crawler-volume:/workspace/volume

volumes:
  paper-crawler-volume:
    driver: local