services:
  paper-crawler-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: paper-crawler-dev
    container_name: paper-crawler-dev
    expose:
      - 8000
    tty: true
    environment:
      - COLLECTION_PERIOD=24 # in hours
      - DATABASE_URL=postgresql://postgres:postgres@paper-crawler-dev-db:5432/database
      - SUMMARIZER_URL=http://localhost:8000
    env_file:
      - .env
    volumes:
      - ..:/workspace
      - paper-crawler-volume:/volume
  
  db:
    image: postgres
    hostname: paper-crawler-dev-db
    container_name: paper-crawler-dev-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    expose:
      - 5432
    volumes:
      - paper-crawler-volume-postgres:/var/lib/postgresql/data
    

volumes:
  paper-crawler-volume:
    driver: local
  paper-crawler-volume-postgres:
    driver: local
  