import datetime
from pydantic import BaseModel

import database


class Paper(BaseModel):
    id: str

    title: str
    abstract: str

    authors: list[str]
    organizations: list[str]

    url: str  # URL to the paper publishment page
    pdf: str  # URL to the PDF of the paper

    journal: str | None
    doi: str | None

    topics: list[str] | None  # List of topics extracted from the paper
    summary: str | None  # Summary generated by the llm

    published_at: datetime.datetime
    updated_at: datetime.datetime

    @classmethod
    def from_sql(self, paper_row: database.PaperRow):
        paper = Paper(
            id=paper_row.id,
            title=paper_row.title,
            abstract=paper_row.abstract,
            authors=paper_row.authors,
            organizations=paper_row.organizations,
            url=paper_row.url,
            pdf=paper_row.pdf,
            journal=paper_row.journal,
            doi=paper_row.doi,
            topics=paper_row.topics,
            summary=paper_row.summary,
            published_at=paper_row.published_at,
            updated_at=paper_row.updated_at,
        )
        return paper
