import datetime
from pydantic import BaseModel

import database


class Paper(BaseModel):
    id: str

    title: str
    abstract: str

    authors: list[str]
    organizations: list[str]

    url: str  # URL to the paper publishment page
    pdf: str  # URL to the PDF of the paper

    journal: str | None
    doi: str | None

    topics: list[str] | None  # List of topics extracted from the paper
    summary: str | None  # Summary generated by the llm

    published_at: datetime.datetime
    updated_at: datetime.datetime

    @classmethod
    def from_sql(self, paper: database.PaperRow):
        self.id = paper.id
        self.title = paper.title
        self.abstract = paper.abstract
        self.authors = paper.authors
        self.organizations = paper.organizations
        self.url = paper.url
        self.pdf = paper.pdf
        self.journal = paper.journal
        self.doi = paper.doi
        self.topics = paper.topics
        self.summary = paper.summary
        self.published_at = paper.published_at
        self.updated_at = paper.updated_at
