services:
  crawler-dev:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    hostname: crawler
    container_name: pc-crawler-dev
    tty: true
    volumes:
      - ../:/workspace
  db-dev:
    image: postgres:17
    hostname: db
    container_name: pc-db-dev
    expose:
      - "5432"
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database